# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AudioPlaybackManager'
  pod 'VIMediaCache', :git => 'https://github.com/vitoziv/VIMediaCache.git'
  # Pods for iosApp

end
